[tool.poetry]
name = "mp3-from-youtube"
version = "0.1.0"
description = ""
authors = ["Aliaksandr <apxont@disroot.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
